- name: Install Redis
  become: true
  apt:
    name: redis-server
    state: present

- name: Create Redis data directory
  become: true
  register: dir_redis
  file:
    path: "{{ redis_dir }}"
    state: directory
  
- name: Configure Redis
  become: true
  register: conf_redis
  template:
    src: ../files/redis.conf
    dest: /etc/redis/redis.conf

- name: Restart Redis
  become: true
  when: conf_redis.changed
  systemd: 
    name: redis-server
    state: restarted

- name: ufw rules
  become: true
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "6379"